# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='resume',
            name='user_doc',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='resume',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
