# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170612_0521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resume',
        ),
        migrations.DeleteModel(
            name='uploadFile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
